# Generated by Django 3.1.7 on 2021-02-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geolocalization',
            name='zip',
            field=models.CharField(max_length=200),
        ),
    ]
